require 'simple_hl7_parser/segments/segment'

module SimpleHL7Parser
  class OBRSegment
    include Segment

    COLUMN_MAP = {
      set_id:  1,
      placer_order_number:  2,
      filler_order_number:  3,
      universal_service_id:  4,
      priority:  5,
      requested_date_time:  6,
      observation_date_time:  7,
      observation_end_date_time:  8,
      collection_volume:  9,
      collector_identifier:  10,
      specimen_action_code:  11,
      danger_code:  12,
      relevant_clinical_information:  13,
      specimen_received_date_time:  14,
      specimen_source:  15,
      ordering_provider:  16,
      order_callback_phone_number:  17,
      placer_field_1:  18,
      placer_field_2:  19,
      filler_field_1:  20,
      filler_field_2:  21,
      results_rpt_status_chng_date_time:  22,
      charge_to_practice:  23,
      diagnostic_serv_sect_id:  24,
      result_status:  25,
      parent_result:  26,
      quantity_timing:  27,
      result_copies_to:  28,
      parent_results_observation_identifier:  29,
      transportation_mode:  30,
      reason_for_study:  31,
      principal_result_interpreter:  32,
      assistant_result_interpreter:  33,
      technician:  34,
      transcriptionist:  35,
      scheduled_date_time:  36,
      number_of_sample_containers:  37,
      transport_logistics_collected_sample:  38,
      collector_comment:  39,
      transport_arrangement_responsibility:  40,
      transport_arranged:  41,
      escort_required:  42,
      planned_patient_transport_comment:  43,
      procedure_code:  44,
      procedure_code_modifier:  45,
      placer_supplemental_service_information:  46,
      filler_supplemental_service_information:  47,
      medically_necessary_duplicate_procedure_reason:  48,
      result_handling:  49,
      parent_universal_service_identifier:  50,
      observation_group_id:  51,
      parent_observation_group_id:  52,
      alternate_placer_order_number:  53,
      parent_order:  54,
    }
  end
end
